config/routes.rb
Parisrb::Application.routes.draw do
  mount Paris::Root => '/api'
  
  devise_for :users, :controllers => {
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  
  authenticated :user do
    root :to => "talks#index"
    resources :talks
    resources :meetups
    resources :locations
    resources :users
  end
  
  root :to => "home#index", :as => :anon_home

end

app/models/meetup.rb
class Meetup
  include Mongoid::Document
  field :title, type: String
  field :description, type: String
  field :location_id, type: String
  field :scheduled, type: Date
  field :start_hour, type: Time
  field :end_hour, type: Time
  field :meetup_url, type: String
  has_many :talks
  belongs_to :location
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  before_action :set_meetup, only: [:show, :edit, :update, :destroy]

  # GET /meetups
  # GET /meetups.json
  def index
    @meetups = Meetup.all
  end

  # GET /meetups/1
  # GET /meetups/1.json
  def show
  end

  # GET /meetups/new
  def new
    @meetup = Meetup.new
  end

  # GET /meetups/1/edit
  def edit
  end

  # POST /meetups
  # POST /meetups.json
  def create
    @meetup = Meetup.new(meetup_params)

    respond_to do |format|
      if @meetup.save
        format.html { redirect_to @meetup, notice: 'Meetup was successfully created.' }
        format.json { render action: 'show', status: :created, location: @meetup }
      else
        format.html { render action: 'new' }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetups/1
  # PATCH/PUT /meetups/1.json
  def update
    respond_to do |format|
      if @meetup.update(meetup_params)
        format.html { redirect_to @meetup, notice: 'Meetup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetups/1
  # DELETE /meetups/1.json
  def destroy
    @meetup.destroy
    respond_to do |format|
      format.html { redirect_to meetups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meetup
      @meetup = Meetup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meetup_params
      params.require(:meetup).permit(:title, :description, :location_id, :scheduled, :start_hour, :end_hour, :meetup_url)
    end
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/views/meetups/_form.html.erb
<%= simple_form_for(@meetup) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description, as: :text %>
    <%= f.input :location_id, collection: Location.all, as: :select%>
    <%= f.date_select :scheduled, default: Date.today + 30, label: 'Date' %>
    <%= f.time_select :start_hour, default: Date.today + 1 , label: 'Heure de début' %>
    <%= f.time_select :end_hour, default: Date.today + 4, label: 'Heure de fin'  %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/meetups/edit.html.erb
<h1>Editing meetup</h1>

<%= render 'form' %>

<%= link_to 'Show', @meetup %> |
<%= link_to 'Back', meetups_path %>

app/views/meetups/index.html.erb
<h1>Listing meetups</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Location</th>
      <th>Scheduled</th>
      <th>Start hour</th>
      <th>End hour</th>
      <th>Meetup url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @meetups.each do |meetup| %>
    <tr>
      <td><%= meetup.title %></td>
      <td><%= meetup.description %></td>
      <td><%= meetup.location_id %></td>
      <td><%= meetup.scheduled %></td>
      <td><%= meetup.start_hour %></td>
      <td><%= meetup.end_hour %></td>
      <td><%= meetup.meetup_url %></td>
      <td><%= link_to 'Show', meetup %></td>
      <td><%= link_to 'Edit', edit_meetup_path(meetup) %></td>
      <td><%= link_to 'Destroy', meetup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Meetup', new_meetup_path %>

app/views/meetups/new.html.erb
<h1>New meetup</h1>

<%= render 'form' %>

<%= link_to 'Back', meetups_path %>

app/views/meetups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @meetup.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @meetup.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @meetup.location_id %>
</p>

<p>
  <strong>Scheduled:</strong>
  <%= @meetup.scheduled %>
</p>

<p>
  <strong>Start hour:</strong>
  <%= @meetup.start_hour %>
</p>

<p>
  <strong>End hour:</strong>
  <%= @meetup.end_hour %>
</p>

<p>
  <strong>Meetup url:</strong>
  <%= @meetup.meetup_url %>
</p>

<%= link_to 'Edit', edit_meetup_path(@meetup) %> |
<%= link_to 'Back', meetups_path %>