config/routes.rb
Parisrb::Application.routes.draw do
  mount Paris::Root => '/api'
  
  devise_for :users, :controllers => {
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  
  authenticated :user do
    root :to => "talks#index"
    resources :talks
    resources :meetups
    resources :locations
    resources :users
  end
  
  root :to => "home#index", :as => :anon_home

end

app/models/talk.rb
class Talk
  include Mongoid::Document
  field :title, type: String
  field :description, type: String
  field :proposed_on, type: Date
  field :meetup_id, type: String
  field :user_id, type: String
  field :level, type: String
  field :duration, type: Integer
  belongs_to :meetup
  belongs_to :user
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :set_talk, only: [:show, :edit, :update, :destroy]

  # GET /talks
  # GET /talks.json
  def index
    @talks = Talk.all
  end

  # GET /talks/1
  # GET /talks/1.json
  def show
  end

  # GET /talks/new
  def new
    @talk = Talk.new
  end

  # GET /talks/1/edit
  def edit
  end

  # POST /talks
  # POST /talks.json
  def create
    @talk = Talk.new(talk_params.merge({:user_id => current_user.id}))

    respond_to do |format|
      if @talk.save
        format.html { redirect_to @talk, notice: 'Talk was successfully created.' }
        format.json { render action: 'show', status: :created, location: @talk }
      else
        format.html { render action: 'new' }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /talks/1
  # PATCH/PUT /talks/1.json
  def update
    respond_to do |format|
      if @talk.update(talk_params)
        format.html { redirect_to @talk, notice: 'Talk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talks/1
  # DELETE /talks/1.json
  def destroy
    @talk.destroy
    respond_to do |format|
      format.html { redirect_to talks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_talk
      @talk = Talk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def talk_params
      params.require(:talk).permit(:title, :description, :proposed_on, :meetup_id, :user_id, :level, :duration)
    end
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/talks/_form.html.erb
<%= simple_form_for(@talk) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description, as: :text %>
    <%= f.input :proposed_on, as: :date, disabled: :true, default: Date.today  %>
    <%= f.input :meetup_id, collection: Meetup.all, as: :select%>
    <fieldset><legend>Niveau</legend>
    <%= f.collection_radio_buttons :level, [[1, 'Débutant'] ,[5, 'Intermédiaire'],[10, 'Avancé']], :first, :last %>
    </fieldset>
    <fieldset><legend>Durée</legend>
    <%= f.collection_radio_buttons :duration, [[5, '4 min super court'] ,[20, '20 mins un peu de temps'],[60, 'Une heure!?']], :first, :last %>
    </fieldset>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/talks/edit.html.erb
<h1>Editing talk</h1>

<%= render 'form' %>

<%= link_to 'Show', @talk %> |
<%= link_to 'Back', talks_path %>

app/views/talks/index.html.erb
<h1>Listing talks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Proposed on</th>
      <th>Meetup</th>
      <th>User</th>
      <th>Level</th>
      <th>Duration</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @talks.each do |talk| %>
    <tr>
      <td><%= talk.title %></td>
      <td><%= talk.description %></td>
      <td><%= talk.proposed_on %></td>
      <td><%= talk.meetup_id %></td>
      <td><%= talk.user_id %></td>
      <td><%= talk.level %></td>
      <td><%= talk.duration %></td>
      <td><%= link_to 'Show', talk %></td>
      <td><%= link_to 'Edit', edit_talk_path(talk) %></td>
      <td><%= link_to 'Destroy', talk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Talk', new_talk_path %>

app/views/talks/new.html.erb
<h1>New talk</h1>

<%= render 'form' %>

<%= link_to 'Back', talks_path %>

app/views/talks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @talk.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @talk.description %>
</p>

<p>
  <strong>Proposed on:</strong>
  <%= @talk.proposed_on %>
</p>

<p>
  <strong>Meetup:</strong>
  <%= @talk.meetup_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @talk.user_id %>
</p>

<p>
  <strong>Level:</strong>
  <%= @talk.level %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @talk.duration %>
</p>

<%= link_to 'Edit', edit_talk_path(@talk) %> |
<%= link_to 'Back', talks_path %>